apiVersion: v1
kind: Service
metadata:
  name: visa-bff
  labels:
    app: visa-bff
spec:
  selector:
    app: visa-bff
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: visa-bff
spec:
  selector:
    matchLabels:
      app: visa-bff
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      name: visa-bff
      labels:
        app: visa-bff
    spec:
      containers:
        - name: visa-bff
          image: asia.gcr.io/arimac-staging/visa-bff
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: GROUP_SERVICE_URL
              value: http://user-mgt-service:8080/api/user-mgt
            - name: REDIS_URL
              value: redis
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
